stages:
- name: compile
  steps:
  - runScriptConfig:
      image: gcc:latest
      shellScript: cmake install
- name: publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-helloworld:${CICD_EXECUTION_SEQUENCE}
      registry: 127.0.0.1:34499
- name: deployment
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
